
#ESTE ARQUIVO É RESPONSÁVEL POR OBTER AS CHAVES DE SEGURANÇA DA SUA CONTA AWS
#PARA QUE CONSIGA ACESSAR OS RECURSOS E SERVIÇOS DA PROVEDORA CLOUD VIA CÓDIGO

export AWS_ACCESS_KEY_ID="YOUR_AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="YOUR_AWS_SECRET_ACCESS_KEY"
export AWS_DEFAULT_REGION="us-east-1"

aws sts get-caller-identity